name: pr-test

# 1. Runs tests
# 2. Upload coverage

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Bring up DBs
        run: docker-compose -f docker-compose.db.yml up -d

      - name: Run unit tests
        run: cd src && go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: unit
          fail_ci_if_error: true

      - name: Bring up stack
        run: make up

      - name: Run integration tests
        run: cd tests && go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: integration
          fail_ci_if_error: true
